### ISSUE TITLE
[Idea/Feature] Support multiple sets per instances

### ISSUE THREAD

**Issue by Elv13** [mindeunix/clientdb#1]
To really "support" https://github.com/awesomeWM/awesome/issues/1273, this module could use the `awful.prompt` hooks to set the `DESKTOP_STARTUP_ID` env variable for the next client. This way you could save multiple templates per instances, as you could restore them for a specific process instead of an instance.

Tyrannical 2 monkey patch `awful.rules` to implement a chain of responsibility. Eventually I may upstream this (it doesn't break the API, so I can push this into the post 4.0 stable releases). For now, you could copy/paste Tyrannical code and highjack the `props` array builder with your own `clientdb` handler. It would be cleaner than just adding them to the `awful.rules.rules` array.

Edit: Note that it is currently broken for Qt5 apps https://bugs.kde.org/show_bug.cgi?id=373587, it is a regression, but I failed to find out **why** so far. The API support it an claims it is correctly enabled (but it doesn't actually work)

**Comment by mindeunix** [comment]
This code snippet I'm already using for some time, and it's a little more than @llatigid requested.

```lua
-- NOTE: must be memory angry, find a better way to store client properties.
local remember = { }

-- client properties to remember
local properties = {
    boolean = {
        "minimized", "urgent", "ontop", "marked", "hidden",
        "above", "below", "fullscreen", "maximized",
        "sticky", "floating", "titlebar", "skip_taskbar"
    },
    string = { },
    number = { "x", "y", "width", "height" }
}
for kind,_ in pairs(properties) do
    for _,prop in pairs(properties[kind]) do
        awful.client.property.persist("_" .. prop, kind)
    end
end
awesome.connect_signal("exit", function(restarting)
    if not restarting then return end
    for _,c in ipairs(client.get()) do
        for kind,_ in pairs(properties) do
            for _,prop in pairs(properties[kind]) do
                c["_" .. prop] = c[prop]
            end
        end
    end
end)
client.connect_signal("manage", function(c)
     if remember[c.class .. c.name .. c.instance] then -- I seen this client before?
         for kind,_ in pairs(properties) do
            for _,prop in pairs(properties[kind]) do
                c[prop] = remember[c.class .. c.name .. c.instance][prop]
            end
         end
     else
        for kind,_ in pairs(properties) do
            for _,prop in pairs(properties[kind]) do
                if type(c["_"..prop]) ~= "nil" then
                    c[prop] = c["_"..prop]
                end
            end
        end
     end
end)
client.connect_signal("unmanage", function(c)
     remember[c.class .. c.name .. c.instance] = {}
     for kind,_ in pairs(properties) do
         for _,prop in pairs(properties[kind]) do
            remember[c.class .. c.name .. c.instance][prop] = c[prop]
         end
     end
end)
```
ugly, but works for me &trade;

**Comment by Elv13** [comment]
Right (/me OMG someone else than @blueyed who uses the `xprop` API), this solve the first half of the problem better than the `SNID` API. However you still can't implement `ctrl+shift+s` (also known as "Save As") using this code. A small (and untested) possible implementation

```lua
local function open_as(command, template)
   props = load_from_client_db(template)
   
   local pid, snid = awful.spawn(command)

   -- private API, can break at any point in time
   awful.spawn.snid_buffer[snid] = {props} -- [1]==rules, [2] == callbacks table
end
```

**Comment by mindeunix** [comment]
You know me, I will go my own way :-)

First, I do not want to keep all the data in to memory (this can cause problems). Secondly, I do not think that using ```snid``` is the best way to achieve this. Third, there is no point to keep/restore each client properties. And last, my example which I use is really terrible (I want to get rid of it).

I will add a new SQLite column "remember", so only selected clients will be remembered. Table that will store information will contain only client coordinates. To make this module much easier to use I will create a GUI for it (old plans).

![test](http://i.imgur.com/4t8fwCg.png)

WIP.

**Comment by mindeunix** [comment]
I have already completed the GUI part:

![](http://i.imgur.com/6AA8Lqw.png)

almost everything is working properly, but can not find time to finish...

**Comment by blueyed** [comment]
@mindeunix 
Great stuff!
You might want to rename the repo to awesome-clientdb, or awesomewm-clientdb?!

**Comment by mindeunix** [comment]
Thanks for your support, but I stopped further work on this module.
